name: $(date:yyyyMMdd)$(rev:.rr)

pr:
  - master

stages:
  - stage: build
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet build
            workingDirectory: $(working_dir)

  - stage: test
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet test --collect:"XPlat Code Coverage"
            workingDirectory: $(working_dir)

  - stage: pack
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - task: Docker@2
              inputs:
                containerRegistry: 'docker'
                command: 'login'
          - script: |
              docker image build -f dockerfile -t $DOCKER_IMAGE .
              docker image push $DOCKER_IMAGE
            workingDirectory: $(working_dir)
            env:
              DOCKER_IMAGE: $(image_name)
              DOCKER_LOGIN: $(docker_login)
          - task: Docker@2
              inputs:
                containerRegistry: 'docker'
                command: 'logout'

trigger:
  - master

variables:
  - image_name: fredbelotte/p1proj
  - working_dir: $(System.DefaultWorkingDirectory)/p1-project
